version: "3.9"
services:
  wp:
    depends_on: 
      - db
    image: wordpress:6.0-php8.1-fpm-alpine
    volumes:
      - ./data/wp_files:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/custom-conf.ini
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress_user
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
      # - WORDPRESS_CONFIG_EXTRA=
      #   define('WP_HOME','${HOME_URL}');
      #   define('WP_SITEURL','${HOME_URL}');
    networks:
      - net
  db:
    image: mariadb:10.9
    restart: always
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes: 
      - ./data/db_files:/var/lib/mysql
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      - net
  nginx:
    image: nginx:alpine
    depends_on: 
      - wp
    volumes:
      - ./data/wp_files:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 127.0.0.1:${WP_PORT}:80
    restart: always
    networks:
      - net
  adminer:
    image: adminer
    depends_on: 
      - db
    restart: always
    ports:
      - 127.0.0.1:${ADMINER_PORT}:8080
    # environment:
      # - ADMINER_DESIGN=hydra
    networks:
      - net
networks:
  net:
    driver: bridge